import { connectToMongoDB, disconnectFromMongoDB } from "../db.js";
import mongoose from "mongoose";
import Item from "../models/item.model.js";
//Este script añade los 100 items de el array a la base de datos, creado para probar las requests paginadas
const items = [
  "Espada de Hierro",
  "Escudo de Madera",
  "Poción de Vida",
  "Poción de Maná",
  "Arco Largo",
  "Flecha de Acero",
  "Daga Envenenada",
  "Casco de Cuero",
  "Armadura de Placas",
  "Botas de Velocidad",
  "Guantes de Fuerza",
  "Anillo de Protección",
  "Amuleto Mágico",
  "Capa de Invisibilidad",
  "Bastón de Fuego",
  "Libro de Hechizos",
  "Pergamino de Teletransporte",
  "Gema de Poder",
  "Cristal de Hielo",
  "Piedra Filosofal",
  "Llave Antigua",
  "Cofre del Tesoro",
  "Moneda de Oro",
  "Lingote de Plata",
  "Diamante Bruto",
  "Esmeralda Pulida",
  "Rubí Encantado",
  "Zafiro Místico",
  "Poción de Fuerza",
  "Poción de Velocidad",
  "Antídoto",
  "Elixir de Curación",
  "Bomba de Humo",
  "Trampa Explosiva",
  "Cuerda Resistente",
  "Antorcha",
  "Linterna Mágica",
  "Brújula",
  "Mapa del Tesoro",
  "Catalejo",
  "Martillo de Guerra",
  "Hacha de Batalla",
  "Lanza Élfica",
  "Ballesta",
  "Mazo Pesado",
  "Espada Larga",
  "Estoque",
  "Cimitarra",
  "Tridente",
  "Vara Rúnica",
  "Talismán de Suerte",
  "Reliquia Sagrada",
  "Fragmento de Estrella",
  "Núcleo de Energía",
  "Escama de Dragón",
  "Colmillo de Lobo",
  "Pluma de Fénix",
  "Corazón de León",
  "Garra de Grifo",
  "Ala de Murciélago",
  "Veneno de Serpiente",
  "Hierba Curativa",
  "Raíz Mágica",
  "Flor Luminosa",
  "Champiñón Venenoso",
  "Cristal de Energía",
  "Barra de Mithril",
  "Placa de Adamantium",
  "Fragmento de Meteorito",
  "Polvo de Hadas",
  "Esencia Elemental",
  "Frasco de Ácido",
  "Vial de Sangre",
  "Ceniza Volcánica",
  "Escudo Rúnico",
  "Yelmo Dorado",
  "Peto de Batalla",
  "Grebas de Combate",
  "Brazales de Acero",
  "Cinturón de Fuerza",
  "Botas Aladas",
  "Sombrero de Mago",
  "Túnica Élfica",
  "Manto Real",
  "Silbato Encantado",
  "Campana Mística",
  "Espejo Mágico",
  "Reloj de Arena",
  "Frasco Vacío",
  "Saco de Provisiones",
  "Ración de Viaje",
  "Cantimplora",
  "Tienda de Campaña",
  "Manta Térmica",
  "Kit de Herramientas",
  "Kit de Costura",
  "Cerradura Compleja",
  "Ganzúa",
  "Trampa para Osos",
  "Red de Caza",
  "Silbato de Señal",
  "Bandera de Clan"
];
const course = "69a5bcd04af7306b73283047"
const image = "1783957011325-694088616.png"
await connectToMongoDB();
items.forEach(async (name) => {
    try{
        const newItem = new Item({
            name,
            course,
            description: "Mock description",
            image: `image/${course}/items/${image}`
        });
        await newItem.save();
    }   catch(error){
        console.log(error.message);
    }
})
